import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { AuthProvider } from "~/context/auth";
import { ModalContextProvider } from "~/context/modal";
import Modal from "~/components/ui/modal";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <AuthProvider>
        <ModalContextProvider>
          <Modal />
          <body>{children}</body>
        </ModalContextProvider>
      </AuthProvider>
    </html>
  );
}
